# Generated by Django 5.1.5 on 2025-02-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_player',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='favourite_team',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
